complete -c xdotool -xa"getactivewindow getwindowfocus getwindowname getwindowpid getwindowgeometry getdisplaygeometry search selectwindow help version behave behave_screen_edge click getmouselocation key keydown keyup mousedown mousemove mousemove_relative mouseup set_window type windowactivate windowfocus windowkill windowclose windowmap windowminimize windowmove windowraise windowreparent windowsize windowunmap set_num_desktops get_num_desktops set_desktop get_desktop set_desktop_for_window get_desktop_for_window get_desktop_viewport set_desktop_viewport exec sleep"
complete -c xdotool -n"__fish_seen_subcommand_from windowunmap" -l sync -d"only exit once the window has been unmapped (is hidden)"
complete -c xdotool -n"__fish_seen_subcommand_from windowsize" -l usehints -d"Use window sizing hints (like font size in terminals)"
complete -c xdotool -n"__fish_seen_subcommand_from windowsize" -l sync -d"only exit once the window has resized"
complete -c xdotool -n"__fish_seen_subcommand_from windowmove" -l sync -d"only exit once the window has moved"
complete -c xdotool -n"__fish_seen_subcommand_from windowmove" -l relative -d"make movements relative to the current window position"
complete -c xdotool -n"__fish_seen_subcommand_from windowminimize" -l sync -d"only exit once the window has minimized (is not visible)"
complete -c xdotool -n"__fish_seen_subcommand_from windowmap" -l sync -d"only exit once the window has been mapped (is visible)"
complete -c xdotool -n"__fish_seen_subcommand_from windowfocus" -l sync -d"only exit once the window has focus"
complete -c xdotool -n"__fish_seen_subcommand_from windowactivate" -l sync -d"only exit once the window is active (is visible + active)"
complete -c xdotool -n"__fish_seen_subcommand_from type" -l window -d"specify a window to send keys to <windowid>"
complete -c xdotool -n"__fish_seen_subcommand_from type" -l terminator -d"similar to --args, specifies a terminator that TERM"
complete -c xdotool -n"__fish_seen_subcommand_from type" -l file -d"specify a file, the contents of which will be <filepath>"
complete -c xdotool -n"__fish_seen_subcommand_from type" -l delay -d"delay between keystrokes <milliseconds>"
complete -c xdotool -n"__fish_seen_subcommand_from type" -l clearmodifiers -d"reset active modifiers (alt, etc) while typing"
complete -c xdotool -n"__fish_seen_subcommand_from type" -l args -d"how many arguments to expect in the exec command. This is N"
complete -c xdotool -n"__fish_seen_subcommand_from set_window" -l urgency -d"set the window's urgency hint. URGENT"
complete -c xdotool -n"__fish_seen_subcommand_from set_window" -l role -d"set the window's role string ROLE"
complete -c xdotool -n"__fish_seen_subcommand_from set_window" -l overrideredirect -d"set override_redirect. OVERRIDE"
complete -c xdotool -n"__fish_seen_subcommand_from set_window" -l name -d"set the window name (aka title) NAME"
complete -c xdotool -n"__fish_seen_subcommand_from set_window" -l icon-name -d"set the window name while minimized/iconified NAME"
complete -c xdotool -n"__fish_seen_subcommand_from set_window" -l classname -d"set the window's classname CLASSNAME"
complete -c xdotool -n"__fish_seen_subcommand_from set_window" -l class -d"set the window's class CLASS"
complete -c xdotool -n"__fish_seen_subcommand_from set_desktop" -l relative -d"Move relative to the current desktop. Negative values OK"
complete -c xdotool -n"__fish_seen_subcommand_from search" -l title -d"DEPRECATED. Same as --name."
complete -c xdotool -n"__fish_seen_subcommand_from search" -l sync -d"Wait until a search result is found."
complete -c xdotool -n"__fish_seen_subcommand_from search" -l shell -d"print results as shell array WINDOWS=( ... )"
complete -c xdotool -n"__fish_seen_subcommand_from search" -l screen -d"only search a specific screen. Default is all screens"
complete -c xdotool -n"__fish_seen_subcommand_from search" -l prefix -d"use prefix (max 16 chars) for array name STRWINDOWS"
complete -c xdotool -n"__fish_seen_subcommand_from search" -l pid -d"only show windows belonging to specific process"
complete -c xdotool -n"__fish_seen_subcommand_from search" -l onlyvisible -d"matches only windows currently visible"
complete -c xdotool -n"__fish_seen_subcommand_from search" -l name -d"check regexp_pattern against the window name"
complete -c xdotool -n"__fish_seen_subcommand_from search" -l maxdepth -d"set search depth to N. Default is infinite."
complete -c xdotool -n"__fish_seen_subcommand_from search" -l limit -d"break search after N results"
complete -c xdotool -n"__fish_seen_subcommand_from search" -l desktop -d"only search a specific desktop number"
complete -c xdotool -n"__fish_seen_subcommand_from search" -l classname -d"check regexp_pattern against the window classname"
complete -c xdotool -n"__fish_seen_subcommand_from search" -l class -d"check regexp_pattern against the window class"
complete -c xdotool -n"__fish_seen_subcommand_from search" -l any -d"Windows matching any condition will be reported"
complete -c xdotool -n"__fish_seen_subcommand_from search" -l all -d"Require all conditions match a window. Default is --any"
complete -c xdotool -n"__fish_seen_subcommand_from mouseup" -l window -d"specify a window to send keys to <windowid>"
complete -c xdotool -n"__fish_seen_subcommand_from mouseup" -l clearmodifiers -d"reset active modifiers (alt, etc) while typing"
complete -c xdotool -n"__fish_seen_subcommand_from mousemove_relative" -l sync -d"only exit once the mouse has moved"
complete -c xdotool -n"__fish_seen_subcommand_from mousemove" -l sync -d"only exit once the mouse has moved"
complete -c xdotool -n"__fish_seen_subcommand_from mousemove" -l screen -d"which screen to move on, default is current screen SCREEN"
complete -c xdotool -n"__fish_seen_subcommand_from mousedown" -l window -d"specify a window to send keys to <windowid>"
complete -c xdotool -n"__fish_seen_subcommand_from mousedown" -l clearmodifiers -d"reset active modifiers (alt, etc) while typing"
complete -c xdotool -n"__fish_seen_subcommand_from keyup" -l window -d"send keystrokes to a specific window WINDOW"
complete -c xdotool -n"__fish_seen_subcommand_from keyup" -l repeat -d"How many times to repeat the key sequence TIMES"
complete -c xdotool -n"__fish_seen_subcommand_from keyup" -l repeat-delay -d"DELAY milliseconds between repetitions DELAY"
complete -c xdotool -n"__fish_seen_subcommand_from keyup" -l delay -d"Use DELAY milliseconds between keystrokes DELAY"
complete -c xdotool -n"__fish_seen_subcommand_from keyup" -l clearmodifiers -d"clear active keyboard modifiers during keystrokes"
complete -c xdotool -n"__fish_seen_subcommand_from key" -l window -d"send keystrokes to a specific window WINDOW"
complete -c xdotool -n"__fish_seen_subcommand_from key" -l repeat -d"How many times to repeat the key sequence TIMES"
complete -c xdotool -n"__fish_seen_subcommand_from key" -l repeat-delay -d"DELAY milliseconds between repetitions DELAY"
complete -c xdotool -n"__fish_seen_subcommand_from key" -l delay -d"Use DELAY milliseconds between keystrokes DELAY"
complete -c xdotool -n"__fish_seen_subcommand_from key" -l clearmodifiers -d"clear active keyboard modifiers during keystrokes"
complete -c xdotool -n"__fish_seen_subcommand_from keydown" -l window -d"send keystrokes to a specific window WINDOW"
complete -c xdotool -n"__fish_seen_subcommand_from keydown" -l repeat -d"How many times to repeat the key sequence TIMES"
complete -c xdotool -n"__fish_seen_subcommand_from keydown" -l repeat-delay -d"DELAY milliseconds between repetitions DELAY"
complete -c xdotool -n"__fish_seen_subcommand_from keydown" -l delay -d"Use DELAY milliseconds between keystrokes DELAY"
complete -c xdotool -n"__fish_seen_subcommand_from keydown" -l clearmodifiers -d"clear active keyboard modifiers during keystrokes"
complete -c xdotool -n"__fish_seen_subcommand_from getwindowgeometry" -l shell -d"output shell variables for use with eval"
complete -c xdotool -n"__fish_seen_subcommand_from getwindowgeometry" -l prefix -d"use prefix for shell variables names (max 16 chars) STR"
complete -c xdotool -n"__fish_seen_subcommand_from getmouselocation" -l shell -d"output shell variables for use with eval"
complete -c xdotool -n"__fish_seen_subcommand_from getmouselocation" -l prefix -d"use prefix for shell variables names (max 16 chars) STR"
complete -c xdotool -n"__fish_seen_subcommand_from exec" -l terminator -d"similar to --args, specifies a terminator that TERM"
complete -c xdotool -n"__fish_seen_subcommand_from exec" -l sync -d"only exit when the command given finishes. The default"
complete -c xdotool -n"__fish_seen_subcommand_from exec" -l args -d"how many arguments to expect in the exec command. This is N"
complete -c xdotool -n"__fish_seen_subcommand_from click" -l window -d"specify a window to send click to WINDOW"
complete -c xdotool -n"__fish_seen_subcommand_from click" -l repeat -d"number of times to click. Default is 1 REPEATS"
complete -c xdotool -n"__fish_seen_subcommand_from click" -l delay -d"delay in milliseconds between clicks. MILLISECONDS"
complete -c xdotool -n"__fish_seen_subcommand_from click" -l clearmodifiers -d"reset active modifiers (alt, etc) while typing"
complete -c xdotool -n"__fish_seen_subcommand_from behave_screen_edge" -l quiesce -d"quiet time period after activating that no MILLISECONDS"
complete -c xdotool -n"__fish_seen_subcommand_from behave_screen_edge" -l delay -d"delay before activating. During this time, MILLISECONDS"
